Initial POSIXct support
r-world-devs/cohortBuilder pull request #36
Opened 2024-10-28 08:16 UTC by galachad

2024-10-31 13:21 UTC, krystian8207 requested changes
Good job! I have a few small comments, ptal.

2024-10-31 13:21 UTC, krystian8207 commented on NEWS.md
> +# shinyCohortBuilder (development version)
```suggestion
# cohortBuilder (development version)
```

2024-10-31 13:21 UTC, krystian8207 commented on R/filter.R
> +filter.date_time_range <- function(type, id, name, ..., description = NULL,
Can we have `datetime` instead of `date_time`? It's a common word in programming so I think it would be simpler.

2024-10-31 13:21 UTC, krystian8207 commented on R/source_tblist.R
> +  if (!is.na(idx))
Please use `{` and `}` for all the `if` conditions (as this follows tidyverse styleguide).

2024-10-31 13:21 UTC, krystian8207 commented on R/source_tblist.R
> +      # Convert the variable to POSIXct if it's not already
Please check comments I add for other filters (keep_na etc.). The comments are crucial for extracting code blocks for reproducible code.

2024-11-01 19:40 UTC, krystian8207 requested changes
LGTM. One simple comment regarding news.md file.

2024-11-01 19:40 UTC, krystian8207 commented on NEWS.md
> +* Add new `data_time_filter` that handle POSIXct type.
`datetime_range` filter that can be applied to POSIXct type data.

2024-11-04 07:35 UTC, galachad commented on NEWS.md
> +* Add new `data_time_filter` that handle POSIXct type.
```suggestion
* Add new `datatime_filter` that handle POSIXct type.
```

2024-11-04 10:28 UTC, krystian8207 approved these changes
lgtm

2024-11-04 11:44 UTC, merged